### ISSUE TITLE
Zsoltárok könyve

### ISSUE THREAD

**Issue by HarmaiGabor** [borazslo/szentiras.hu#106]
Sziasztok!

Azon tűnődtem, hogy nem lehetne a Zsoltárok könyvébe egy olyan kivételt beépíteni, hogy ott a "fejezet"-eket ne fejezeteknek hívja, hanem "zsoltároknak"? Tehát pl. "22. fejezet" helyett "22. zsoltár"

**Comment by briff** [comment]
Szerintem jó ötlet. Megcsináltam f1f5aae789a32bdeb9a3e682f93b7b880a3146d0
