### ISSUE TITLE
Keresési eredményeknél sorrend

### ISSUE THREAD

**Issue by borazslo** [borazslo/szentiras.hu#111]
Ha fejezetenkénti csoportosítást kérünk, akkor a fejezeten belül a megfelelő versek azért sorszám szerint sorrendbe legyenek (nem folytatólagosság esetén: [...] ). Ne pedig össze vissza.

**Comment by briff** [comment]
Nem össze-vissza van, hanem relevancia szerint, de valóban zavaró és kéne bele az [...]

**Comment by borazslo** [comment]
Esetleg a [...] után is egy space?
