### ISSUE TITLE
XLS olvasására spout

### ISSUE THREAD

**Issue by briff** [borazslo/szentiras.hu#114]
Elvileg drasztikusan gyorsulhat a beolvasás:
https://github.com/box/spout

**Comment by briff** [comment]
már elkezdtem

**Comment by borazslo** [comment]
Annál jobb. :)

**Comment by briff** [comment]
@borazslo Az UF.xls betöltése hunspell nélkül 10p alatt van. Ez fejlődés?

**Comment by borazslo** [comment]
RUF_szovegforras.xlsm hunspell nélkül dropboxból letöltve localhoston 6p alatt van valamicskével. Szóval fejlődés.

**Comment by briff** [comment]
localhoston? ez alatt mit értesz? mindenesetre most rátoltam a stagingre a RUF-ot, 15-30mp a letöltés a dropboxból, hunspell nélkül az egész 15 perc. Akkor így lassabb?

**Comment by borazslo** [comment]
localhoston: MAC OSx-en futó apache-php-mysql (MAMP) fejlesztői környezetben. (A vagrantot még épp nem telepítettem. )
A 15 perc RUF így többnek tűnik, de nem mértem a stagingen. Viszont a legutolsó phpexcel verzió a mysqldump-nál mindig elszállt (memória, idő vagy valami más miatt). És egyébként is eléggé fel kellett húzni a memória limitet, hogy egyáltalán eljusson odáig. Szóval ha kisebb az erőforrás igénye már az is előrehaladás.

**Comment by briff** [comment]
A memóriafogyasztása lényegesen kisebb. A beolvasás lehet, hogy lassabb, mert az egész sort olvassa és konvertálja php-tömbbé mindig. 
3000 sor beolvasásáról csináltam statiszikát:
https://blackfire.io/profiles/24fb2362-1ff1-431f-9d34-a58811c36dda/graph

Varázsoltam még a hunspell-lel is, hogy csak azt a típust szótövezze, amit kell, illetve ez nem külön lépés, hanem (ha nincs kikapcsolva) rögtön megcsinálja.
