### ISSUE TITLE
Importáláskor elnyelt betű

### ISSUE THREAD

**Issue by borazslo** [borazslo/szentiras.hu#116]
http://staging.szentiras.hu/KNB/Lk12,46 : Hiányzik a legelső "m" betű pedig a forrás KNB_szovegforrasl.xlsm-ben benne van. 

- Eddig ez az egyetlen ismert eset. 
- Az élő oldal adatbázisában kézzel kijavítottam, de ez nem megoldás.
- UpdateTextsCommand probléma?

**Comment by briff** [comment]
Az adatbázisban 70-es jelenséggel benne van, 60-assal (ami a megjelenített) nincs. 
Ez nem konzisztens az xls-sel.

**Comment by briff** [comment]
A laravel5 branchen hibátlanul lement az updateTexts, úh térjünk vissza rá, ha beraktam a masterre

**Comment by briff** [comment]
Visszamerge-öltem a laravel5 branchet, úgyhogy a következő updateText a masteren elvileg megoldja.
