### ISSUE TITLE
KNB Ám 1,1

### ISSUE THREAD

**Issue by molnarm** [borazslo/szentiras.hu#117]
Üres az első vers (hosszabb idézetben vagy fejezet nézetben is):
http://szentiras.hu/KNB/%C3%81m1,1

**Comment by briff** [comment]
Úgy tűnik, a legutóbbi frissítés problémás lett. A stagingen is rossz, viszont a saját gépemen a laravel5 branchről futtattott updateTexttel jól néz ki, a #116-hoz hasonlóan.
