### ISSUE TITLE
Elfogy a memória

### ISSUE THREAD

**Issue by briff** [borazslo/szentiras.hu#120]
Hát ezzel nem tudom, mit tudunk csinálni.
Egyrészt szövegfrissítés végén:
 [ErrorException]
  proc_open(): fork failed - Cannot allocate memory

Másrészt a syslogban a postfix írogatja, hogy nincs memória.

Plusz: Frissítés közben felmegy 1.5GB-ra a használat. Erősen az a gyanúm, hogy tényleg kevés a memóriánk a gépben :(

@borazslo Ötlet?

**Comment by borazslo** [comment]
- Egy vészmegoldás lehet, hogy a sokat zabáló munkálatokat (pl. frissítés) akkor futtatjuk, amikor más nem nagyon fut/használódik. (Akár "kézzel" kikapcsolva ideiglenesen dolgokat késő éjjeleken.)
- Meg át is írhatjuk a frissítést, hogy ne egyen annyit. (Részletekben fusson? Bár a fájl beolvasása maga elég erőforrás igényes.)
- De előbb megnézem / megpróbálom megtudni, hogy mi is a memória plafon. Mivel virtuális gépünk van, hátha a plafon tágítható.

**Comment by borazslo** [comment]
Szerintem nem szimpla memória probléma van a háttérben.

1. A `free -h` szerint 8.0T a memóriánk és alig 1.2GB-t használunk. (Az `ulimit -a` szerint unlimited a virtuális memóriánk.) Kissé soknak érzem azért. :)
2. A fork failed (vagy failed to fork) hibát egy időben (pár hete) rendszeresen láttam egészen kis igényű parancsoknál is (pl. `git rev-parse --verify HEAD 2> /dev/null]`) kb. véletlenszerűen. Vagyis a hibüzenetet nem feltétlenül a memóriaigényes feladat produkálja. (A php is szokik olyat produkálni, hogy valamely library-t nem tudja betölteni mert "cannot allocate memory". 
3. Nekem most többször is lefutott a szövegfrissítés (KNB, hunspell-el együtt is). (Viszont a végén azért hibát kaptam, de "csak" ilyet:   `The process "indexer --config /etc/sphinxsearch/sphinx_staging.conf --all --rotate" exceeded the timeout of 60 seconds.`). A `top` mutatta közben, hogy akár 90-100%-on is pörög a CPU, de memóriát nem jelzett.

Aktuális tippem, hogy a miserend.hu egyik cron-ban futó feladatában van valami ami elszáll (több jel is erre utal). Megpróbálom kiiktatni.

**Comment by briff** [comment]
megint nem megy a keresés, de maga a supervisor sem indul el, ami elindulva tartaná, fork failed-el száll el.

**Comment by briff** [comment]
Összesen 2GB RAM van a VM-ünknek, szerintem simán lehet, hogy az már ennyi mindenhez kevés.

**Comment by borazslo** [comment]
Sajnos nem csak egyszer állt le. A hétvégén legalább négyszer-ötször indítottam újra. 

Viszont a rendszergazda segített: a `free -h` most már nem az egészségtelen/valótlan 8.0T memóriáról számol be, hanem beállította a szabad memóriát 4GB-ra. Újra reménykedhetünk.

**Comment by borazslo** [comment]
Egy hete nem állt le a kereső. Reményteljes rekord. :)
