### ISSUE TITLE
szerver leállás

### ISSUE THREAD

**Issue by Zolta** [borazslo/szentiras.hu#121]
Ma délelőtt óta a szentiras.hu nem elérhető. 
a katolikus.hu szintén off

**Comment by briff** [comment]
Köszi, valóban, elég sokminden áll azon a környéken - mivel nem csak a szentiras.hu-t érinti, bízom benne, hogy a rendszergazdák tudatában vannak a problémának.

**Comment by borazslo** [comment]
Karbantartás van a Pázmány Péter Katolikus Egyetem szerverszobájában. Az eredeti tervek szerint délután öt körül véget kellene érnie.
