### ISSUE TITLE
CORS beállítások eltűntek?

### ISSUE THREAD

**Issue by molnarm** [borazslo/szentiras.hu#126]
A külső oldalakról JavaScriptből indított API kéréseket a szerver elutasítja:

`XMLHttpRequest cannot load http://szentiras.hu/api/idezet/Zsolt23/KNB.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://molnarm.github.io' is therefore not allowed access.`

(Az API oldalon van néhány hivatkozás, amit az igemutató plugin szintén felismer, ezeket sikeresen meg is jeleníti, mivel itt a kérést tartalmazó oldal maga a `szentiras.hu`)

**Comment by briff** [comment]
Igen, a laravel 5re upgrade során alighanem elromlott

**Comment by briff** [comment]
@molnarm meg tudnád nézni staging-en, hogy jó-e?

**Comment by molnarm** [comment]
@briff úgy tűnik, jó lesz, köszi!

**Comment by briff** [comment]
Kint prodon
