### ISSUE TITLE
KNB Lk11,11

### ISSUE THREAD

**Issue by borazslo** [borazslo/szentiras.hu#133]
A KALDI  FORDITASBAN LUKACS 11.11-BEN,HIANYZIK AZ HA KENYERET KER,AZTAN HALAT MEG UTOB TOJAST...aki  itt olvassa azt hiheti, hogy Lukacsnal nincs benne  a kenyer...

**Comment by briff** [comment]
A kenyeres rész csak egyes forrásokban van benne. A Nestle-Aland 28 kiadásban nincs benne a kenyér, ezért a legújabb fordításokban sincs. Nem hiba.
