### ISSUE TITLE
API kereső jelenség

### ISSUE THREAD

**Issue by macakzsolt** [borazslo/szentiras.hu#138]
http://szentiras.hu/api/search/Isten  csak a BD és a RUF bibliákból jelenít meg adatokat, ha az "Isten" kifejezésre rákeresek. Vajon mi lehet ennek az oka?

**Comment by briff** [comment]
Lehet, h a túl sok találat miatt. (Úgy emlékszem, hogy az API keresőben egyenrangúak a fordítások, így ha egy kulcsszó több fordításban is benne van ugyanabban a versben, akkor véletlenszerűen - vagy talán valami belső azonosító szerint - választja a fordítást.)

**Comment by macakzsolt** [comment]
Eddigi lekérdezéseim alapján úgy tűnik következetes a dolog mindig ugyan az a két fordítás jelenik csak meg tehát a DB és a RUF több egymást követő napon is próbáltam… De pl. ha beírom azt, hogy „a” akkor is csak a fönti két biblia jelenik meg csak. Azonban, ha beírom, hogy „valami” akkor pontosan 1000 találat jön le az összes bibliából… lehet, hogy ennyi van.   (a fönti eredményeket a DataGridView be lekérdezve WindowsForm -ban kaptam sorszámlálóval kiegészítve) de webes felületen is csak a DB és a RUF szerepel a fönt említett esetekben.

Mennyi a lekérdezés limit? 
Ha van, limit jó lenne, ha lehetne az egy adott fordításra is szűkíteni a http://szentiras.hu/api/search/akármi találati eredményét,  amit most tudomásom szerint nem igazán lehet korlátozni. Így nem kellene lekérni az összes biblia találatát egy adott alkalmazásba és utólag valamilyen Gridben szűrni… és relevánsabb eredmény is születhetne egy-egy kifejezésre váló keresésnél, számlálásánál… stb.

**Comment by macakzsolt** [comment]
Per pillanat egyáltalán nem működik a keresés sem az API sem a kereső mező…  
Azaz pl.
http://szentiras.hu/api/search/bocsát
{"refResult":[],"fullTextResult":null}
A főoldal:
http://szentiras.hu/kereses/search?textToSearch=bocsát

Üres oldalt ad vissza.

**Comment by briff** [comment]
Újraindítottam a keresőmotort. Légyszi tesztelésre a staging.szentiras.hu oldalt használd.

**Comment by macakzsolt** [comment]
OK a rendben...
staging.szentiras.hu -t  lehet, hogy érdemes jelezni valamelyik fejlesztőknek szánt oldalon, de lehet, hogy csak nekem nem jött át eddig... :-)
