### ISSUE TITLE
Szövegek licensze?

### ISSUE THREAD

**Issue by molnarm** [borazslo/szentiras.hu#144]
Kaptam egy e-mailt, amiben azt kérdezi valaki, hogy mi van, ha egyszer megszűnik az oldal, megkaphatná-e a biztonság kedvéért az adatbázist. Attól függetlenül, hogy nekem sincs meg és egyébként se hiszem, hogy menne vele bármire a jelenlegi formátumban, elgondolkodtatott a kérdés.

A [fordítások leírásánál](http://szentiras.hu/forditasok) említetek engedélyeket, de nem világos, hogy ez mit jelent pontosan, laikusként nem tudom, hogy mire és hogyan használhatom a szövegeket*. Nyilván a szerző nem korlátozná a hozzáférést :-) , de a fordítók munkája miatt ez valószínűleg ennél bonyolultabb.

\* pl. mi van, ha nem lehet telepíteni a fejlesztőkörnyezetet (#140) és így újra implementálni a régi hiányzó funkciót, letölthetek-e egy egész fordítást az API-n keresztül, hogy magamnak csináljak belőle ebookot...

**Comment by briff** [comment]
A szövegeket kifejezetten a szentiras.hu-n való felhasználásra kaptuk meg (kivétel a Károli). A fordítás szerzői jog alatt áll (sőt, vicces módon a görög eredeti is, mert ugye, hogy mi a görög eredeti, az már egy szerkesztői munka).
Az adatbázist emiatt nem tudjuk kiadni (maga az adatbázis is szerzői jogvédelem alatt áll).

**Comment by molnarm** [comment]
Köszi, továbbítom a választ.
