### ISSUE TITLE
HTTPS támogatás

### ISSUE THREAD

**Issue by molnarm** [borazslo/szentiras.hu#145]
(Emlékeztetőként, az [igemutatós probléma](https://github.com/molnarm/igemutato/issues/34) kapcsán merült fel.)

Azóta megnéztem, és nem is egyszerűen az van, hogy a szentiras.hu-nak nincs tanúsítványa, mert a https://szentiras.hu címen a miserend.hu jön be! (Aminek a tanúsítványa meg lejárt januárban, úgyhogy a saját domainjére se érvényes.)

**Comment by szepeviktor** [comment]
Mintkettő egy IP-n van, és bizonyása nincs SNI támogatás a webszerveren.
`193.225.109.9`

**Comment by Pengeszikra** [comment]
Van infó, arról, hogy mikor lesz az API https-en keresztül is elérhető?

**Comment by borazslo** [comment]
Van valakinek bevált helye ahonnan szerez SSL bizonyítványt? Nekünk a legegyszerűbb is megfelel. Arra nincs valami igen olcsó / ingyenes megoldás valahol?

**Comment by molnarm** [comment]
Szerintem jó lenne a [letsencrypt](https://github.com/molnarm/igemutato/issues/34#issuecomment-292310574). Még nem használtam (de tervezem), de teljesen ingyenes és lehet automatizálni a megújítást is.

**Comment by briff** [comment]
@molnarm Ha kipróbáltad, szólj :) Én is néztem már. Az https://www.sslforfree.com/ ad egy egyszerűbb felületet hozzá, de beküldi a kitudjakinek a privát kulcsot, úgyhogy az nem annyira nyerő.

**Comment by szepeviktor** [comment]
A *gyári* kliens igen veszélyes, és úgy látom, hogy nem hozzáértőknek írták.
Ez az ultra egyszerű Pythons szkript megbízható (10+ helyen használom) https://github.com/veeti/manuale

**Comment by szepeviktor** [comment]
Az ügyfeleimnél preferálom a RapidSSL-t (a Symantec van mögötte) a Let's Encrypt-tel szemben.
https://cheapsslsecurity.com/sslbrands/rapidssl.html
Itt $20-ért 3 évig nyugta van az embernek. Az OCSP szervert érdemes monitorozni.

**Comment by gyuris** [comment]
Nekem is kellene [ehhez](https://www.drupal.org/sandbox/bubu/2805297) a https://szentiras.hu, mivel jelenleg blokkolja a böngésző a betöltést a HTTPS hiánya miatt („A vegyes aktív „http://szentiras.hu/api/ref/Zak%2012,10-11;13/KNB” tartalom betöltése blokkolva”).
Én egyébként a Let’s Encrypt-et használom, a tárhelyszolgáltatóm adja a cPanel-lel a lehetőséget. Egyszer kellett beállítanom, azóta nem volt vele dolgom, szépen újítgatja időnként.

**Comment by gyuris** [comment]
Csak ösztönzésül a HTTPS és a Let’s Encrypt mellett: https://www.hwsw.hu/hirek/58091/lets-encrypt-tanusitvanykibpcsato-https-biztonsag.html

**Comment by briff** [comment]
Rajta vagyok az ügyön, csak most hirtelen valami gebasz történt, eltűnt a szerver alólam. Lehet, hogy a letsencrypt miatt ?

**Comment by briff** [comment]
Lehet próbálni. https://szentiras.hu/

**Comment by Pengeszikra** [comment]
Köszönet!
Tökéletesen működik a https-es lekérés:  [szentiras api js](https://codepen.io/Omrega/pen/GMVKLL)

**Comment by borazslo** [comment]
Lejárt a certificate, azaz az automatikus megújítása.

**Comment by gyuris** [comment]
Hm... Mi a gond? Nincs automatikus megújítás beállítva?

**Comment by briff** [comment]
Ugy látszik nincs. Majd megoldom.

**Comment by briff** [comment]
Na, az automatikus megújítást még nem sikerült belőnöm.
Egyelőre manuálisan megcsináltam megint, kb így (majd ebből kell egy script):
./certbot-auto certonly -d szentiras.hu
(itt web root-tal, a public könyvtárból)
cd /etc/letsencrypt/live/
cat fullchain.pem privkey.pem > chain_priv_combined.pem
service haproxy restart

**Comment by gyuris** [comment]
Fiúk, lejárt a HTTPS tanúsítvány.

> szentiras.hu uses an invalid security certificate. The certificate expired on 2018. június 1. 20:13.

**Comment by briff** [comment]
köszi, upgrade-eltem, 3 hónap múlva megint elromlik :)

**Comment by molnarm** [comment]
El is romlott: https://szentiras.hu :-(

**Comment by briff** [comment]
és már frissítettem is :)

**Comment by gyuris** [comment]
Ismét: 2018. december 30-án lejárt. Meg kellene újítani.

**Comment by briff** [comment]
> @briff @borazslo Erre a problémára cron-ból futtatható ez a szkript
> https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/cert-expiry.sh
> Minden szerveren alapból telepítve.

A certbot is jó lenne, ha támogatná a haproxy-t.

**Comment by borazslo** [comment]
Ismét. :(
Hol ven ez az cucc / hogyan kell manuálisan frissíten? 
/etc/letsencrpyt ?

**Comment by briff** [comment]
Így kell manuálisan frissíteni: 
sudo -i
./certbot-auto certonly -d szentiras.hu
(itt web root-tal, a ......./public könyvtárból)
cd /etc/letsencrypt/live/szentiras.hu
cat fullchain.pem privkey.pem > chain_priv_combined.pem
service haproxy restart

Csakhogy nem megy a certbot-auto :(
 No module named pip.__main__; 'pip' is a package and cannot be directly executed

**Comment by briff** [comment]
https://github.com/certbot/certbot/issues/6824
A debiant frissítenünk kell, h működjön. Vagy teljesen manuálisan kéne, a certbot nélkül.
Erre most nagyon nem lesz időm :(

**Comment by briff** [comment]
Vagy itt van egy harmadik lehetőség, ez elvileg működik 
https://community.letsencrypt.org/t/pip-error-with-certbot-auto/88200/5

**Comment by molnarm** [comment]
Van bármi fejlemény ezzel kapcsolatban? Már több, mint egy hónapja nem megy a HTTPS, én is kapom a visszajelzéseket, hogy a bővítmények nem működnek.
Előre is köszi!

**Comment by briff** [comment]
megvan, kösz a figyelmeztetést (átírtam a scriptet ez alapján: https://community.letsencrypt.org/t/pip-error-with-certbot-auto/88200/5) - ha a script frissül, lehet, hogy megint át kell.

**Comment by briff** [comment]
Kivettem a haproxyt az apache alól, érdekes kaland volt, de igazából már nem kell :)
Így a certbot teljesen automatikusan tud frissíteni (./certbot renew), DE nem fog működni, ezért kéne majd írni valami sed scriptet, ami lecseréli a python hívást.

**Comment by ahornyai** [comment]
Én mindig cloudflare proxyt szoktam használni, ingyenes, elrejti a weboldal ipjet, botolásos támadások ellen véd és ami itt lényeges, ingyenes, automatikusan megújuló httpst ad.

**Comment by briff** [comment]
> Én mindig cloudflare proxyt szoktam használni, ingyenes, elrejti a weboldal ipjet, botolásos támadások ellen véd és ami itt lényeges, ingyenes, automatikusan megújuló httpst ad.

Köszi! Ha összeomlik a certbot (egyelőre stabil) jön a cloudflare akkor
