### ISSUE TITLE
Keresés egyáltalán nem működik

### ISSUE THREAD

**Issue by gyuris** [borazslo/szentiras.hu#158]
Ööö... valami nagyobb gubanc van. A keresés egyáltalán nem ad vissza semmilyen találatot. Se a gyorskereső háttérben kommunikáló tippjei nem működnek, sem maga a részletes keresés. Firefox, Chrome nem számít.

A keresés API sem túl bőbeszédű választ ad a [példára](http://szentiras.hu/api/search/bocs%C3%A1t):
```
{"refResult":[],"fullTextResult":null}
```

**Comment by briff** [comment]
időnként megdöglik a kereső

**Comment by gyuris** [comment]
Újra megdöglött...
