### ISSUE TITLE
CORS megint nem jó

### ISSUE THREAD

**Issue by molnarm** [borazslo/szentiras.hu#173]
(Mint a #126 korábban).

"Cross-Origin kérés blokkolva: Az azonos eredet házirend nem engedélyezi a távoli erőforrás olvasását innen: https://szentiras.hu/api/idezet/1Kor12,3b-7.12-13/KNB. (Ok: A CORS kérés sikertelen volt)."

**Comment by briff** [comment]
Szia! Megnéztem ezzel a toollal https://resttesttest.com/ és ezzel: https://www.test-cors.org
https://szentiras.hu/api/idezet/1Kor12,3b-7.12-13/KNB Firefox-szal és Chrome-mal is.
Mindkét esetben benn volt az Access-Control-Allow-Origin header a válaszban.
Tudsz írni részleteket, hogy hogyan lehet a hibát előidézni?

**Comment by molnarm** [comment]
E-mailben kaptam eredetileg.
Most ránéztem jobban, úgy tűnik, hogy ezzel nincs baj, akkor nem működik a dolog, ha sima HTTP-vel akarjuk használni az API-t, mert az redirectel HTTPS-re.
Majd csinálok egy frissítést a bővítményemhez, hogy már fixen HTTPS-t használjon.
