### ISSUE TITLE
KG - hivatkozások tagolása

### ISSUE THREAD

**Issue by krisek** [borazslo/szentiras.hu#184]
A Károli fordításban a hivatkozások számos helyen nem megfelően tagoltak. Az alábbi (pszeudókódként is olvasható) python kód és reguláris kifejezések valamelyest javítják a problémákat.

```
  if chapter['chapterid'] + '.' + str(verse['num']) == '1Kgs.12.21':
    verse['cite'] = re.sub('Vers 21-24: v. ö. ','',verse['cite'])
  verse['cite2'] = re.sub(r'\.(\d)(\D+);', r'; \1\2 ', verse['cite'])
  verse['cite3'] = re.sub(r'(\d) (Móz|Pét|Thess|Tim|Kor|Ján|Sám|Krón)', r'\1\2', verse['cite2'])
  if verse['cite2'] != verse['cite3']:
    verse['cite3'] = re.sub(r'\. (\d)(Móz|Pét|Thess|Tim|Kor|Ján|Krón|Sám)', r'; \1\2', verse['cite3'])
  verse['cite4'] = re.sub(r'\. (Márk|Jel|Filem|Gal|Kol|Tit|Zsid|Eféz|Ésa|Dán|Mát|Ján)', r'; \1', verse['cite3'])
```

**Comment by borazslo** [comment]
Tudsz adni konkrét linket, hogy könnyen láthassam, ha sikerült megcsinálni? Köszi.

**Comment by krisek** [comment]
https://github.com/krisek/HunKar/

Az eredeti Excel táblázat javítása eddig nem volt prioritás, ha van jó érv rá, akkor nekiállhatok :smile:

**Comment by borazslo** [comment]
Én az adatbázisban nem szeretnék kézzel belenyúlni, mert az nem követhető eléggé, így
- vagy a közvetlen szövegforrásban javítanám az evidens hibákat
- vagy a megjelenítésben

De ha valami tök evidensen elgépelős szöveghiba, akkor miért ne a forrásban javítsuk, és miért kelljen plusz erőforrás a témára? A KNB szövegforrásból egyetlen paranccsal be tudom importálni a teljes szöveget (meg is lepődtem, hogy működik most is), én így tenném a KG-val is. Igaz, hogy az nálunk tényleg nem priroritás. De azért miért ne foglalkozhatnánk vele?

(Harmai G-vel lehet hogy kommunikálandó a téma, ő talán nem jár errefelé.)

**Comment by krisek** [comment]
Szerintem nyugodtan lezárhatjuk ez a jegyet, Gáborral már beszéltünk róla és valóban az Excel-ben kéne javítani.

Egyszer majd nekiállok.
