### ISSUE TITLE
HTML kód a vers fejlécben

### ISSUE THREAD

**Issue by ahornyai** [borazslo/szentiras.hu#186]
Sok helyen láttam már (elsősorban a Magyar Bibliatársulat újfordítású Bibliája (2014) fordításban, többiben nem néztem), hogy a vers fejlécekben, mint pl itt: https://szentiras.hu/RUF/Mt9 (https://ahornyai.me/i/bqysp.png) egy sortörés van, csak nincs parseolva.
Ezeket a feltehetőleg véletlen folytán ottmaradt kódokat szerintem egy egyszerű replacel el lehetne tüntetni.

**Comment by briff** [comment]
Köszi! Sajnos asszem a szövegforrás nem konzisztens, de megnézem majd.
