### ISSUE TITLE
Keresés nagyon sok szóra hibával válaszol

### ISSUE THREAD

**Issue by borazslo** [borazslo/szentiras.hu#187]
Olyan egyszerű kifejezésekre is hibát generál (és a gyors kereső sem reagál rá), mint:
tovább, teljesedik, fogad, stb.

- Nem tűnik ékezet gondnak.
- Mintha KNB gond lenne csak. translation=3

**Comment by briff** [comment]
A sphinx search indexelés nem futott le az update után valami miatt.
