### ISSUE TITLE
Napi olvasmányok API

### ISSUE THREAD

**Issue by borazslo** [borazslo/szentiras.hu#4]
**No description provided.**
https://bitbucket.org/borazslo/szentiras-hu/issue/4/napi-olvasm-nyok-api

**Comment by borazslo** [comment]
Az https://igenaptar.katolikus.hu/ oldalon egy ideje már a szentmisén elhangzó szöveg vannak pontosan. Könyörgések, zsoltárok, fohászok is benne vannak. Bár API nincs ott, de előbb csinálunk nekik, mint hogy az egészet megcsináljuk itt magunk.

**Comment by gyuris** [comment]
Mint felhasználó: Amikor még csak a funkció neve volt meg, akkor reménykedtem, de így már nem érdekes... Szerintem ennek nincs sok értelme.  A Szentírás rendszeres olvasása a liturgikus beosztás alapján vicc kategória. Van egy katolikus mítosz erről, hogy a liturgián elolvassuk a Szentírást, de valóság az, hogy a vasárnapi beosztás a Szentírás 12%-t öleli fel, a teljes hátköznapi+vasárnapi pedig 30,3%-t a három, ill. a két év alatt. 
Aki olvasni akarja a Szentírást és nem csak a liturgikus kivonatokat, az egész más beosztásokat követ. A leghíresebb ilyen Gyürki László beosztása, amit a Jeromos Társulat jelentetett meg. Sok évvel ezelőtt, a Biblia évéhez én is csináltam ilyen beosztásokat: https://halld.ujevangelizacio.hu/

Szóval, csalódáskeltő, hogy ez a funkció csupán egy újabb liturgikus beosztás tükör, ilyenből van elég. Felhasználóként ilyet találni sokfelé. A piac már régóta le van fedve.
Nem akartok egy rendes, "olvasd végig" típusú személyes beosztást is készíteni? Annak tényleg lenne piaci rése.

**Comment by briff** [comment]
> Mint felhasználó: Amikor még csak a funkció neve volt meg, akkor reménykedtem, de így már nem érdekes... Szerintem ennek nincs sok értelme. A Szentírás rendszeres olvasása a liturgikus beosztás alapján vicc kategória. Van egy katolikus mítosz erről, hogy a liturgián elolvassuk a Szentírást, de valóság az, hogy a vasárnapi beosztás a Szentírás 12%-t öleli fel, a teljes hátköznapi+vasárnapi pedig 30,3%-t a három, ill. a két év alatt. Aki olvasni akarja a Szentírást és nem csak a liturgikus kivonatokat, az egész más beosztásokat követ. A leghíresebb ilyen Gyürki László beosztása, amit a Jeromos Társulat jelentetett meg. Sok évvel ezelőtt, a Biblia évéhez én is csináltam ilyen beosztásokat: https://halld.ujevangelizacio.hu/
> 
> Szóval, csalódáskeltő, hogy ez a funkció csupán egy újabb liturgikus beosztás tükör, ilyenből van elég. Felhasználóként ilyet találni sokfelé. A piac már régóta le van fedve. Nem akartok egy rendes, "olvasd végig" típusú személyes beosztást is készíteni? Annak tényleg lenne piaci rése.

Nem pont ezt csinálta meg @gabre?

**Comment by borazslo** [comment]
Ez egy 2014-es okafogyott issue. 

1) Magyarországon érvényes katolikus direktórium / napi olvasmány API-val nincs is a magyar piacon. Az igenaptar.katolikus.hu ami legtöbb infót tartalmazza de az egész adatstruktúrájával nem sokra megy a halandó. A zsolozsma XML öröknaptárját használva itt van szerintem JSON-al a legteljesebb fejlődő akármi: https://szentjozsefhackathon.github.io/napi-lelki-batyu/naptar.html 

De ez nem a szentiras.hu scope-ja. Tehát ez itten closed és nincs szükség rá.

2) igen, @gabre pont csinált egy olvassuk-végig-a-szentírást funkciót. De az is igazából más issue. De annak lehet piaca és az lehet scope-ja a szentiras.eu-nak.

**Comment by briff** [comment]
Ja, szerintem is, amit más megcsinál, csak linkeljük be, kivéve ha szeretnénk mondjuk más fordításokban mutatni a napi olvasmányt. Mondjuk ennek még akár értelme is lenne, de ami nem scope, hogy a szentiras.hu szolgáltasson adatot.
