### ISSUE TITLE
PDF-generálás

### ISSUE THREAD

**Issue by briff** [borazslo/szentiras.hu#64]
xetex-hel csinálhatunk szépen formázott PDF-et, esetleg PNG-t.
Példa:

![image](https://cloud.githubusercontent.com/assets/1804204/3903404/71e7640a-22cb-11e4-9e81-49cd185f5a42.png)

\documentclass[11pt]{article}
\usepackage{fontspec}
\usepackage[hungarian]{babel}
\setmainfont[Ligatures=TeX]{Linux Libertine O}
\begin{document}

\section*{Káldi-Neovulgáta / Ezekiel jövendölése / Ez 9,1-7;10,18-22}

\subsection*{A város lerombolása}

És hallottam, amint nagy hanggal kiáltotta: »Elérkezett a város bűnhődése! Mindenki tartsa kezében öldöklő fegyverét!« És íme, hat férfi jött az úton az észak felé néző felső kapu felől; mindegyikük kezében pusztító eszköz volt. Az egyik férfi közülük gyolcsba volt öltözve, és írószer volt az oldalán. Beléptek és megálltak az ércoltárnál. Ekkor Izrael Urának dicsősége elszállt a kerubról, amely felett volt, a ház küszöbéhez, és hívta a gyolcsba öltözött férfit, akinek írószer volt az oldalán. Azt mondta neki az Úr: »Járd be Jeruzsálem városát és jelöld meg tau-betűvel a férfiak homlokát, akik siránkoznak és bánkódnak mindazon utálatosság miatt, ami benne történik!« És hallottam, amint azt mondta nekik: »Menjetek keresztül a városon, kövessétek őt és öldököljetek; szemetek ne irgalmazzon, ne könyörüljetek; öreget és ifjút, szüzet, kisdedet és asszonyt öljetek meg irgalmatlanul, de senkit se öljetek meg, akin tau-t láttok. A szentélyemnél kezdjétek!« Megkezdték tehát az idős férfiakon, akik a ház előtt voltak. Azt mondta nekik: »Rajta! Fertőzzétek meg a házat és töltsétek meg megöltekkel az udvarokat!« Azok kimentek és megölték a város lakóit.

\subsection*{Az Úr kivonul a templomból}

Akkor az Úr dicsősége átvonult a templom küszöbén, és megállt a kerubok felett. Ekkor a kerubok felemelték szárnyaikat és felemelkedtek a földről előttem. Amikor kivonultak, a kerekek is követték őket, megálltak az Úr háza keleti kapujának bejáratánál, és Izrael Istenének dicsősége volt felettük. Ezek azok az élőlények, amelyeket Izrael Istene alatt láttam a Kebár folyó mellett; ekkor megértettem, hogy kerubok voltak. Négy arca volt mindegyiknek és négy szárnya volt mindegyiknek, és emberi kézhez hasonló valami volt szárnyaik alatt. Az arcuk teljesen olyan volt, mint azok az arcok, amelyeket a Kebár folyó mellett láttam, úgyszintén alakjuk is; és mindegyikük azon igyekezett, hogy arccal előre haladjon.

\end{document}

**Comment by gyuris** [comment]
Nem lenne egyszerűbb a HTML-ből CSS-sel és [WeasyPrint](https://weasyprint.org/) vagy [Paged.js](https://www.pagedjs.org/) PDF-et generálni?

**Comment by briff** [comment]
> Nem lenne egyszerűbb a HTML-ből CSS-sel és [WeasyPrint](https://weasyprint.org/) vagy [Paged.js](https://www.pagedjs.org/) PDF-et generálni?

Szeretem az elválasztás lehetősége miatti sokkal szebb tipográfiát. Ezért lett LaTeX.
Viszont mivel könyvet végülis nem generálunk, ezért talán még az is elég lenne, ha lenne egy printre alkalmas CSS-ünk, és akkor jöhetnek az egyéb megoldások (no meg ez egy olyan feature, amit ebben a formában simán elengedtem volna).

**Comment by borazslo** [comment]
Felhasználói oldalról ami izgalmas fícsör nyomtatás terén:
- Adott részt kiválasztottam és sallangmentesen tudjam nyomtatni, mert imán majd használom. Ehhez elég lehet CSS meg ilyenek. Sima ügy.
- Kiválasztok egy pár soros idézetet és szeretném kinyomtatni mindenkinek, mondjuk 16 embernek.  Mondjuk három is ráfér egy A4-es lapra és felvágnám. Akkor ne kelljen valahogy word-be átmásolni és ott egymás alá rakosgatni, hanem ha lehetséges oldja meg. Na, ez egy nagy truváj. Szerintem van piaca, de nem biztos hogy top prioritás.

**Comment by briff** [comment]
Ránéztem mindkét javasolt cuccra. Mindkettő tetszik, és elvileg mindkettő tudja a szükséges tipográfiai dolgokat. A több példányos nyomtatásnál viszont kell egy olyan feature, hogy ne vágja szét a bekezdést lapozásnál. Van erre CSS feature, de nem biztos, hogy mindkettő tudja. Bár ez végképp nem prio (egy oldalnál hosszabb idézetnél meg értelmetlen).

**Comment by briff** [comment]
Kipróbáltam a paged.js-t. Nem illeszkedik jól.
De szerencsére fölösleges most már minden ilyesmi. Most már van magyar elválasztás a böngészőkben, sőt, engedelmeskednek annak a CSS-szabálynak, hogy a részleteket ne vágja ketté a lap mentén, szépen működik most minden az új verzióban.
